sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - .eslintcache
matrix:
  include:
    - node_js: "8"
      env: PERCY_ENABLE=1
    - node_js: "7"
      env: PERCY_ENABLE=0
    - node_js: "6"
      env: PERCY_ENABLE=0
    - node_js: "4"
      env: PERCY_ENABLE=0
before_install:
  - yarn --version
script:
  - yarn run test
  - yarn run test:integration react-percy
  - yarn run test:integration react-percy-storybook
