sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - .eslintcache
matrix:
  include:
    - node_js: "8"
      env: PERCY_ENABLE=1
    - node_js: "7"
      env: PERCY_ENABLE=0
    - node_js: "6"
      env: PERCY_ENABLE=0
    - node_js: "4"
      env: PERCY_ENABLE=0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn --version
script:
  - yarn lint
  - yarn test
  - yarn test:integration react-percy
  - yarn test:integration react-percy-storybook
