# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: "6"
      UNIT_TEST: "true"
      COVERAGE: "true"
    - nodejs_version: "8"
      UNIT_TEST: "true"
      COVERAGE: "true"


# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version

  - npm install -g yarn

  # install modules
  - yarn install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - yarn --version
  # run tests
  - yarn lint
  - yarn build
  - yarn test --ci

build:
  off
